hobby_event/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('create_event/', views.create_event, name="create_event"),
    path('event_terminal/<int:event_id>/', views.create_event_terminal, name="create_event_terminal"),
    path('single_event/<int:event_id>/', views.single_event, name="single_event"),
    path('all_events/', views.all_events, name="all_events"),
    path('edit_event/<int:event_id>/', views.edit_event, name="edit_event"),
    path('my_events/', views.my_events, name="my_events"),
    path('event_participators/<int:event_id>/', views.event_participators, name="event_participators"),
    path('hide_show_event/<int:event_id>/', views.hide_show_event, name="hide_show_event"),
    path('signup_for_event/<int:event_id>', views.signup_for_event, name="signup_for_event")
]

hobbyin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('external_page.urls')),
    path('hobby_event/', include('hobby_event.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hobby_event/models.py
from django.db import models
from django.contrib.auth.models import User
from djangospam.akismet import moderator as akismet
from django.utils import timezone
from external_page.models import Instructor, Hobby

# Create your models here.
class HobbyEvent(models.Model):
    event_host = models.ForeignKey(
        Instructor,
        on_delete=models.CASCADE,
    )
    hobby = models.ForeignKey(
        Hobby,
        on_delete=models.CASCADE,
    )
    event_name = models.CharField(max_length=128, null=True, blank=False)
    datetime = models.DateTimeField(blank=False, null=True)
    city = models.CharField(max_length=64, null=True, blank=False)
    city_district = models.CharField(max_length=64, null=True, blank=False)
    zip_code = models.CharField(max_length=6, null=True, blank=False)
    address = models.CharField(max_length=64, null=True, blank=False)
    location_name = models.CharField(max_length=64, null=True, blank=True)
    price = models.PositiveIntegerField(default=0, blank=False, null=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    is_active = models.BooleanField(default=False)
    is_accepted = models.BooleanField(default=False)
    is_hidden = models.BooleanField(default=False)
    event_color_red = models.PositiveIntegerField(default=255, null=False)
    event_color_green =  models.PositiveIntegerField(default=255, null=False)
    event_color_blue = models.PositiveIntegerField(default=255, null=False)
    created_time = models.DateTimeField(auto_now_add=True, null=False, blank=True)

    @property
    def has_happened(self):
        return timezone.now() > self.datetime

    def __str__(self):
        try:
            string = '"' + self.event_name + '"' + " by " + self.event_host.first_name + " " + self.event_host.last_name
        except:
            string = "event_name_error"
        return string

class HobbyEventSignup(models.Model):
    hobby_event = models.ForeignKey(
        HobbyEvent,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
    )
    first_name = models.CharField(max_length=32, null=False, blank=False)
    last_name = models.CharField(max_length=32, null=False, blank=False)
    email = models.CharField(max_length=64, blank=False, null=False, unique=False)
    telephone = models.CharField(max_length=16, blank=True, null=True)
    is_success = models.BooleanField(default=False)
    is_removed = models.BooleanField(default=False)

    def __str__(self):
        try:
            string = self.first_name + " " + self.last_name + " to " + self.hobby_event.event_name
        except:
            string = "event_signup_name_error"
        return string

class VisitHobbyEvent(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True
    )
    hobby_event = models.ForeignKey(
        HobbyEvent,
        on_delete=models.CASCADE,
    )
    datetime = models.DateTimeField(auto_now_add=True, blank=False, null=True)

    def __str__(self):
        if self.user == None:
            string = "Anonymous visited " + self.hobby_event.event_name
        else:
            string = self.user.email + " visited " + self.hobby_event.event_name
        return string

class EventSearch(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True
    )
    search_string = models.CharField(max_length=128, null=True, blank=False)
    zip_code_search = models.CharField(max_length=128, null=True, blank=False)
    datetime = models.DateTimeField(auto_now_add=True, blank=False, null=True)

    def __str__(self):
        if self.user == None:
            this_user = 'Anonymous'
        else:
            this_user = '"' + self.user.email + '"'

        if self.search_string == None:
            this_search_string = 'nothing'
        else:
            this_search_string = '"' + self.search_string + '"'

        if self.zip_code_search == None:
            this_zip_code_search = 'empty zip code search'
        else:
            this_zip_code_search = 'zip code: "' + self.zip_code_search + '"'

        string = this_user + ' searched for: ' + this_search_string + ' and ' + this_zip_code_search
        return string

try:
    akismet.register(HobbyEvent)
except akismet.AlreadyModerated:
    pass

try:
    akismet.register(HobbyEventSignup)
except akismet.AlreadyModerated:
    pass

try:
    akismet.register(VisitHobbyEvent)
except akismet.AlreadyModerated:
    pass

try:
    akismet.register(EventSearch)
except akismet.AlreadyModerated:
    pass

hobby_event/views.py
from django.shortcuts import render
from .forms import CreateEventForm
from .models import HobbyEvent, HobbyEventSignup, VisitHobbyEvent, EventSearch
from external_page.models import Hobby, Instructor
from external_page.views import edit_profile, logout
from django.contrib import messages
import hobbyin.functions as functions
import random

colors = [(123,205,47), (119,172,236), (236,219,84), (240,237,229), (252,169,133), (209,255,244)]

# Create your views here.
def create_event(request):
    if functions.is_instructor(request):
        status = functions.check_user_valid_profile(request)
        if status == 'not_valid':
            request.method = "GET"
            messages.info(request, 'Necessary information is still missing, fill them in before getting started.')
            return edit_profile(request)
        elif status == 'not_active':
            messages.error(request, 'Your account is inactive, contact maxhxie@gmail.com and we will help you.')
            return logout(request)

        current_user = request.user
        if request.method == "POST":
            event_object = HobbyEvent.objects.create(event_host=instructor, hobby=instructor.hobbies, is_active=True)
            color = random.choice(colors)
            event_object.event_color_red = color[0]
            event_object.event_color_green = color[1]
            event_object.event_color_blue = color[2]
            event_object.save()
            form = CreateEventForm(request.POST, instance=event_object)
            if form.is_valid():
                form.save()
                messages.info(request, 'Last step, double check so that all information is correct.')
                request.method = "GET"
                return create_event_terminal(request, event_object.id)

            else:
                messages.error(request, 'Your event could not be created, double check so that everything is correct.')
                return render(request, 'create_event_page.html', context={'form': form, 'type': 'create', 'spam_uri': 'https://www.spelapaintball.com/#wpcf7-f2197-o1'})
        else:
            form = CreateEventForm()
            return render(request, 'create_event_page.html', context={'form': form, 'type': 'create', 'spam_uri': 'https://www.spelapaintball.com/#wpcf7-f2197-o1'})

    else:
        messages.error(request, 'You are not logged in.')
        return all_events(request)



def create_event_terminal(request, event_id):
    if functions.is_instructor(request):
        this_user = functions.get_this_user(request)
        try:
            this_event = HobbyEvent.objects.get(pk=event_id)
        except HobbyEvent.DoesNotExist:
            messages.error(request, 'Där gick något snett, försök igen.')
            return create_events(request)

        if this_event.event_host.user == this_user:
            if not this_event.is_accepted:
                if request.method == "POST":
                    this_event.is_accepted = True
                    this_event.save()
                    request.method = "GET"

                    messages.success(request, 'Ditt evenemang har skapats!')
                    return single_event(request, event_id)

                else:
                    return render(request, 'event_terminal_page.html', context={'this_event': this_event})
            else:
                messages.error(request, 'Du har redan publicerat det här evenemanget.')
                return single_event(request, event_id)
        else:
            messages.error(request, 'Du har inte tillgång till det där evenmanget. Dubbelkolla så att du är inloggad på rätt konto.')
            return create_events(request)
    else:
        messages.error(request, 'Du är inte inloggad som instruktör.')
        return all_events(request)



def single_event(request, event_id):
    if request.user.is_authenticated:
        status = functions.check_user_valid_profile(request)
        if status == 'not_valid':
            request.method = "GET"
            messages.info(request, 'Det saknas fortfarande nödvändig information om dig. Fyll i dem för att komma igång.')
            return edit_profile(request)
        elif status == 'not_active':
            messages.error(request, 'Ditt konto är inte aktivt, kontakta maxhxie@gmail.com så hjälper vi dig.')
            return logout(request)

    this_user = functions.get_this_user(request)

    try:
        this_event = HobbyEvent.objects.get(pk=event_id)
    except HobbyEvent.DoesNotExist:
        messages.error(request, 'Det där evenemanget existerar inte längre.')
        return all_events(request)

    VisitHobbyEvent.objects.create(user=this_user, hobby_event=this_event)

    if this_event.event_host.user == this_user or (this_event.is_hidden == False and this_event.is_active == True and this_event.is_accepted == True and this_event.has_happened == False):
        if this_event.is_accepted == False:
            return create_event_terminal(request, this_event.id)
    else:
        if this_event.has_happened:
            messages.error(request, 'Det här evenemanget har passerat')
        else:
            messages.error(request, 'Det här evenemanget går inte längre att ses.')
        return all_events(request)

    try:
        HobbyEventSignup.objects.get(hobby_event=this_event, user=this_user, is_success=True)
        signed_up = True
    except HobbyEventSignup.DoesNotExist:
        signed_up = False

    return render(request, 'single_event_page.html', context={'this_event': this_event, 'this_user': this_user, 'signed_up': signed_up, 'spam_uri': 'https://www.spelapaintball.com/#wpcf7-f2197-o1'})



def all_events(request):
    """
    Filter and sort all events on five factors:
        1. is_active, is_accepted, is_hidden: Do not include events that does not meet these criteria.
        2. search_hobby_event: Filter away events that does not match the search string.
        3. event_id: Sort by having the most recent events first. (Secondary priority sort)
        4. event.has_happened: Do not include all events that already has happened.
        5. input_zip_code: Sort by having the closest events first. (Primary priority sort)
    """

    if request.user.is_authenticated:
        status = functions.check_user_valid_profile(request)
        if status == 'not_valid':
            request.method = "GET"
            messages.info(request, 'Det saknas fortfarande nödvändig information om dig. Fyll i dem för att komma igång.')
            return edit_profile(request)
        elif status == 'not_active':
            messages.error(request, 'Ditt konto är inte aktivt, kontakta maxhxie@gmail.com så hjälper vi dig.')
            return logout(request)

    this_user = functions.get_this_user(request)

    search_hobby_event = request.GET.get('search_hobby_event')
    input_zip_code = request.GET.get('input_zip_code')

    #Filter away events that does not match the search string.
    if search_hobby_event != None or input_zip_code != None:
        EventSearch.objects.create(user=this_user, search_string=search_hobby_event, zip_code_search=input_zip_code)

    if search_hobby_event != None and search_hobby_event != "":
        event_list1 = HobbyEvent.objects.filter(event_name__icontains=search_hobby_event, is_active=True, is_accepted=True, is_hidden=False)
        event_list3 = HobbyEvent.objects.filter(city__icontains=search_hobby_event, is_active=True, is_accepted=True, is_hidden=False)
        event_list4 = HobbyEvent.objects.filter(city_district__icontains=search_hobby_event, is_active=True, is_accepted=True, is_hidden=False)
        try:
            hobby = Hobby.objects.get(hobby_name__iexact=search_hobby_event)
            event_list2 = HobbyEvent.objects.filter(hobby=hobby, is_active=True, is_accepted=True, is_hidden=False)
            temp_list = event_list1 | event_list2 | event_list3 | event_list4

        except Hobby.DoesNotExist:
            hobby = None
            event_list2 = None
            temp_list = event_list1 | event_list3 | event_list4

        event_list = temp_list.distinct()

        if len(event_list) == 0:
            messages.error(request, 'Vi kunde inte hitta några evenemang för den här hobbyn.')
            request.method = "GET"

    else:
        hobby = None
        event_list = HobbyEvent.objects.filter(is_active=True, is_accepted=True, is_hidden=False)

    #Sort by having the most recent events first. (Secondary priority sort)
    event_list = event_list.order_by('-id')

    #Do not include events that already has happened
    event_list = [event for event in event_list if event.has_happened == False]

    worked, event_list, error = functions.sort_by_proximity(event_list, input_zip_code, request)
    if worked == False and error != None:
        messages.error(request, error)

    return render(request, 'all_events_page.html', context={'event_list': event_list, 'hobby': hobby, 'search_hobby_event': search_hobby_event, 'input_zip_code': input_zip_code})



def my_events(request):
    if request.user.is_authenticated:
        status = functions.check_user_valid_profile(request)
        if status == 'not_valid':
            request.method = "GET"
            messages.info(request, 'Det saknas fortfarande nödvändig information om dig. Fyll i dem för att komma igång.')
            return edit_profile(request)
        elif status == 'not_active':
            messages.error(request, 'Ditt konto är inte aktivt, kontakta maxhxie@gmail.com så hjälper vi dig.')
            return logout(request)

    if functions.is_instructor(request):
        this_instructors_events = HobbyEvent.objects.filter(event_host=request.user.instructor).order_by('-datetime')
        return render(request, 'my_events_page.html', context={'event_list': this_instructors_events})
    else:
        messages.error(request, 'Du är inte inloggad som instruktör.')
        return all_events(request)



def edit_event(request, event_id):
    if request.user.is_authenticated:

hobby_event/templates/all_events_page.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block extra_css %}
{% endblock extra_css %}

{% block extra_head %}
{% endblock extra_head %}

{% block bodyclass %}landing-page sidebar-collapse{% endblock bodyclass %}
{% block body %}
    {% include "html_parts/message_banner.html" %}
    <!-- Navbar -->
    {% include "html_parts/navbar1.html" with color_on_scroll="none" navbar_class=""%}
    <div class="wrapper">

        <div class="section section-tabs" id="our-offerings">
            <div class="container">
                {% if user.instructor %}
                <div class="text-center">
                    <a class="btn btn-primary btn-round btn-lg" href="{% url 'create_event' %}" style="color:white; background-color:#2CA8FF;"><strong><i class="now-ui-icons arrows-1_share-66"></i> {% trans 'Create event' %}</strong></a>
                </div>
                {% endif %}
                {% include 'djangospam/form.html' %}
                <form class="form" method="get" action="{% url 'all_events' %}">
                    <div class="card-body">
                        <div class="input-group form-group-no-border">
                            <span class="input-group-addon">
                                <i class="now-ui-icons ui-1_zoom-bold"></i>
                            </span>
                            <input type="text" class="form-control" id="search_hobby_event" name="search_hobby_event" value="{% if search_hobby_event %}{{ search_hobby_event }}{% endif %}" onkeyup="scroll_alt()" placeholder="Search for event here...">
                        </div>
                        <input type="submit" class="btn btn-primary" value="Sök">
                    </div>
                </form>
                {% if event_list|length != 0 %}
                    <div class="row">
                    {% for event in event_list %}
                        <div class="col-md-10 col-lg-8 col-xl-6 ml-auto mr-auto">
                            <!-- Tabs with Background on Card -->
                            <div class="card" style="cursor:pointer;" onclick="window.location='{% url 'single_event' event.id %}'">
                                <ul class="nav nav-tabs nav-tabs-neutral justify-content-center" role="tablist" data-background-color="orange">
                                    <li class="nav-item">
                                        <a class="nav-link"><strong>{{ event.event_name|upper }}</strong></a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link active"><i class="now-ui-icons users_single-02"></i>{{ event.hobbyeventsignup_set.all|length }}</a>
                                    </li>
                                </ul>
                                {% if event.is_active == True and event.is_accepted == True and event.is_hidden == False and event.has_happened == False %}
                                    <div class="card-body" style="max-height:500px; background-color:rgba({{ event.event_color_red }},{{ event.event_color_green }},{{ event.event_color_blue }}, 1.0);">
                                {% else %}
                                    <div class="card-body" style="max-height:500px; background-color:rgba(200, 200, 200, 1.0);">
                                {% endif %}
                                    <table class="table-responsive">
                                        <tbody>
                                            <tr><td style="padding-right:10px;">Time:</td><td>{{ event.datetime|date:'d M H:i, Y' }}</td></tr>
                                            <tr><td style="padding-right:10px;">Place:</td><td>{{ event.address }}, {{ event.city_district }}, {{ event.city }} {% if location_name %}({{ event.location_name }}){% endif %}</td></tr>
                                            <tr><td style="padding-right:10px;">Price:</td><td>{% if event.price > 0 %}{{ event.price }} kr{% else %}Gratis{% endif %}</td></tr>
                                            <tr><td style="padding-right:10px;">Host:</td><td>{{ event.event_host.first_name|title }} {{ event.event_host.last_name|title }}</td></tr>
                                        </tbody>
                                    </table>
                                    {% if event.description %}
                                        <hr>
                                        <div class="text-center">{{ event.description }}</div>
                                    {% endif %}
                                </div>
                            </div>
                            <!-- End Tabs on plain Card -->
                        </div>
                        {% if forloop.counter|divisibleby:2 %}
                            </div>
                            <div class="row">
                        {% endif %}
                    {% endfor %}
                    </div>
                {% else %}
                    <h3 class="text-center">We could not find any events with this search</h3>
                    <div class="text-center">
                        <a href="{% url 'all_events' %}" class="btn btn-primary btn-round btn-lg" style="color:white; background-color:#2CA8FF;">Go back</a>
                    </div>
                {% endif %}
            </div>
        </div>

        {% if user.is_authenticated %}
        <div class="section section-contact-us text-center" id="work-with-us">
            <div class="container">
                <h2 class="title">{% trans 'You are now logged in as' %}</h2>
                <h3>{{ user.instructor.first_name }} {{ user.instructor.last_name }}</h3>
                <div class="row">
                    <div class="col-lg-6 text-center col-md-8 ml-auto mr-auto">
                        <div class="send-button">
                            <a href="{% url 'my_profile' %}" class="btn btn-primary btn-round btn-block btn-lg">{% trans 'To your profile' %}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% include "html_parts/footer.html" %}
    </div>
    <script>
        $(function(){
        $("label[for='id_hobbies_0']").hide()
        });
    </script>
{% endblock body %}

hobby_event/templates/event_participators_page.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block extra_css %}
{% endblock extra_css %}

{% block extra_head %}
{% endblock extra_head %}

{% block bodyclass %}landing-page sidebar-collapse{% endblock bodyclass %}
{% block body %}
    {% include "html_parts/message_banner.html" %}
    <!-- Navbar -->
    {% include "html_parts/navbar1.html" with color_on_scroll="none" navbar_class=""%}
    <div class="wrapper">
        <div class="section section-contact-us section-javascript" id="javascriptComponents">
            <div class="container">
                <h2 class="title text">
                    {% if this_event.is_active == False %}
                        [NOT ACTIVE]
                    {% elif this_event.is_accepted == False %}
                        [NOT PUBLISHED]
                    {% elif this_event.is_hidden == True %}
                        [LOCKED]
                    {% elif this_event.has_happened == True %}
                        [EXPIRED]
                    {% endif %}
                    <a href="{% url 'single_event' this_event.id  %}">{{ this_event.event_name }}</a>
                </h2>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr><th>Namn</th><th>Telefonnummer</th><th>Email adress</th><th><a href="" class="btn btn-primary btn-block btn-sm" style="margin:0; background-color:#2CA8FF;">Email all prticipants</a></th></tr>
                        </thead>
                        <tbody>
                            {% for signup in this_event.hobbyeventsignup_set.all %}
                                {% if signup.is_success == True and signup.is_removed == False %}
                                    <tr><td><a href="{% url 'profile_with_user' signup.user.id %}">{{ signup.first_name }} {{signup.last_name}}</a></td><td>{{ signup.telephone }}</td><td>{{ signup.email }}</td><td>{% if signup.email != None %}<a href="" class="btn btn-primary btn-block btn-sm" style="margin:0; background-color:#2CA8FF;"><i class="now-ui-icons ui-1_email-85"></i></a>{% endif %}</td></tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% include "html_parts/footer.html" %}
    </div>
<script>
$(function(){
    $("label[for='id_hobbies_0']").hide()
});
</script>
{% endblock body %}

hobby_event/templates/my_events_page.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block extra_css %}
{% endblock extra_css %}

{% block extra_head %}
{% endblock extra_head %}

{% block bodyclass %}landing-page sidebar-collapse{% endblock bodyclass %}
{% block body %}
    {% include "html_parts/message_banner.html" %}
    <!-- Navbar -->
    {% include "html_parts/navbar1.html" with color_on_scroll="none" navbar_class=""%}
    <div class="wrapper">

        <div class="section section-tabs" id="our-offerings">
            <div class="container">
                <div class="text-center">
                    <a class="btn btn-primary btn-round btn-lg" href="{% url 'create_event' %}" style="color:white; background-color:#2CA8FF;"><strong><i class="now-ui-icons arrows-1_share-66"></i> {% trans 'Create event' %}</strong></a>
                </div>
                <h2 class="title text-center">My events</h2>
                {% if event_list|length != 0 %}
                    <div class="row">
                    {% for event in event_list %}
                            <div class="col-md-10 col-lg-8 col-xl-6 ml-auto mr-auto">
                                <!-- Tabs with Background on Card -->
                                <div class="card" style="cursor:pointer;" onclick="window.location='{% url 'single_event' event.id %}'">
                                    <ul class="nav nav-tabs nav-tabs-neutral justify-content-center" role="tablist" data-background-color="orange">
                                        <li class="nav-item">
                                            {% if event.is_active == False %}
                                                <a class="nav-link"><strong>[NO LONGER ACTIVE]</strong> {{ event.event_name|upper }}</a>
                                            {% elif event.is_accepted == False %}
                                                <a class="nav-link"><strong>[NOT PUBLISHED]</strong> {{ event.event_name|upper }}</a>
                                            {% elif event.is_hidden == True %}
                                                <a class="nav-link"><strong>[LOCKED BY YOU]</strong> {{ event.event_name|upper }}</a>
                                            {% elif event.has_happened %}
                                                <a class="nav-link"><strong>[EXPIRED]</strong> {{ event.event_name|upper }}</a>
                                            {% else %}
                                                <a class="nav-link"><strong>{{ event.event_name|upper }}</strong></a>
                                            {% endif %}
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link active"><i class="now-ui-icons users_single-02"></i>{{ event.hobbyeventsignup_set.all|length }}</a>
                                        </li>
                                    </ul>
                                    {% if event.is_active == True and event.is_accepted == True and event.is_hidden == False and event.has_happened == False %}
                                        <div class="card-body" style="max-height:500px; background-color:rgba({{ event.event_color_red }},{{ event.event_color_green }},{{ event.event_color_blue }}, 1.0);">
                                    {% else %}
                                        <div class="card-body" style="max-height:500px; background-color:rgba(200,200,200,1.0);">
                                    {% endif %}
                                        <table class="table-responsive">
                                            <tbody>
                                                <tr><td style="padding-right:10px;">Time:</td><td>{{ event.datetime|date:'d M H:i, Y' }}</td></tr>
                                                <tr><td style="padding-right:10px;">Place:</td><td>{{ event.address }}, {{ event.city_district }}, {{ event.city }} {% if location_name %}({{ event.location_name }}){% endif %}</td></tr>
                                                <tr><td style="padding-right:10px;">Price:</td><td>{% if event.price > 0 %}{{ event.price }} kr{% else %}Gratis{% endif %}</td></tr>
                                                <tr><td style="padding-right:10px;">Arrager:</td><td>{{ event.event_host.first_name|title }} {{ event.event_host.last_name|title }}</td></tr>
                                            </tbody>
                                        </table>
                                        {% if event.description %}
                                            <hr>
                                            <div class="text-center">{{ event.description }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                                <!-- End Tabs on plain Card -->
                            </div>
                            {% if forloop.counter|divisibleby:2 %}
                                </div>
                                <div class="row">
                            {% endif %}
                    {% endfor %}
                    </div>
                {% else %}
                    <h3 class="text-center">You have not created any events</h3>
                {% endif %}
            </div>
        </div>
        {% include "html_parts/footer.html" %}
    </div>
    <script>
        $(function(){
        $("label[for='id_hobbies_0']").hide()
        });
    </script>
{% endblock body %}